version: '3.8'

services:
  dbMongo:
    image: mongo
    container_name: dbMongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    env_file:
      - .env.dev

  app:
    image: nestapp
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - .env.dev
    volumes:
      - .:/app
    command: sleep infinity
    depends_on:
      - dbMongo
